
; Generated by CharPad 2. Assemble with 64TASS or similar.


; General constants:-

TRUE = 1
FALSE = 0
COLRMETH_GLOBAL = 0
COLRMETH_PERTILE = 1
COLRMETH_PERCHAR = 2


; Project constants:-

COLOURING_METHOD = COLRMETH_PERCHAR
CHAR_MULTICOLOUR_MODE = TRUE
COLR_SCREEN = 0
COLR_CHAR_DEF = 6
COLR_CHAR_MC1 = 8
COLR_CHAR_MC2 = 9
CHAR_COUNT = 23
TILE_COUNT = 13
TILE_WID = 2
TILE_HEI = 1
MAP_WID = 20
MAP_HEI = 25
MAP_WID_CHRS = 40
MAP_HEI_CHRS = 25
MAP_WID_PXLS = 320
MAP_HEI_PXLS = 200


; Data block size constants:-

SZ_CHARSET_DATA        = 184
SZ_CHARSET_ATTRIB_DATA = 23
SZ_TILESET_DATA        = 26
SZ_MAP_DATA            = 500


; Data block address constants (dummy values):-

ADDR_CHARSET_DATA        = $2000   ; nb. label = 'charset_data'        (block size = $b8).
ADDR_CHARSET_ATTRIB_DATA = $2800   ; nb. label = 'charset_attrib_data' (block size = $17).
ADDR_TILESET_DATA        = $2900   ; nb. label = 'tileset_data'        (block size = $1a).
ADDR_MAP_DATA            = $2A00   ; nb. label = 'map_data'            (block size = $1f4).



; * INSERT EXAMPLE PROGRAM HERE! * (Or just include this file in your project).



; CHAR SET DATA : 23 (8!byte) chars : total size is 184 ($b8)!bytes.

* = ADDR_CHARSET_DATA
charset_data

!byte $aa,$00,$55,$00,$aa,$00,$55,$00,$00,$fc,$fc,$fc,$fc,$fc,$fc,$00
!byte $00,$3f,$3f,$3f,$3f,$3f,$3f,$00,$00,$fc,$fc,$fc,$fc,$fc,$fc,$00
!byte $00,$3f,$3f,$3f,$3f,$3f,$3f,$00,$00,$fc,$fc,$fc,$fc,$fc,$fc,$00
!byte $00,$3f,$3f,$3f,$3f,$3f,$3f,$00,$00,$fc,$fc,$fc,$fc,$fc,$fc,$00
!byte $00,$3f,$3f,$3f,$3f,$3f,$3f,$00,$00,$fc,$fc,$fc,$fc,$fc,$fc,$00
!byte $00,$3f,$3f,$3f,$3f,$3f,$3f,$00,$00,$fc,$fc,$fc,$fc,$fc,$fc,$00
!byte $00,$3f,$3f,$3f,$3f,$3f,$3f,$00,$00,$fc,$fc,$fc,$fc,$fc,$fc,$00
!byte $00,$15,$15,$15,$15,$15,$15,$00,$00,$54,$54,$54,$54,$54,$54,$00
!byte $00,$2a,$2a,$2a,$2a,$2a,$2a,$00,$00,$a8,$a8,$a8,$a8,$a8,$a8,$00
!byte $00,$00,$00,$00,$00,$00,$00,$00,$bf,$55,$bf,$4f,$ba,$4f,$b7,$6f
!byte $ea,$fd,$f6,$5f,$fa,$ed,$ba,$f5,$aa,$55,$aa,$55,$aa,$55,$aa,$55
!byte $00,$3f,$3f,$3f,$3f,$3f,$3f,$00



; CHAR SET ATTRIBUTE DATA : 23 attributes : total size is 23 ($17)!bytes.
; nb. Upper nybbles = Material, Lower nybbles = Colour.

* = ADDR_CHARSET_ATTRIB_DATA
charset_attrib_data

!byte $06,$09,$0a,$0a,$0b,$0b,$0c,$0c,$0d,$0d,$0e,$0e,$0f,$0f,$0b,$0b
!byte $0b,$0b,$00,$06,$06,$06,$29



; TILE SET DATA : 13 (2x1) tiles : total size is 26 ($1a)!bytes.

* = ADDR_TILESET_DATA
tileset_data

!byte $00,$00,$16,$01,$02,$03,$04,$05,$06,$07,$08,$09,$0a,$0b,$0c,$0d
!byte $0e,$0f,$10,$11,$12,$12,$13,$14,$15,$15



; MAP DATA : 1 (20x25) map : total size is 500 ($1f4)!bytes.

* = ADDR_MAP_DATA
map_data

!byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b
!byte $0b,$0b,$0b,$0b,$0b,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
!byte $00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00,$00,$00,$00,$00
!byte $05,$00,$00,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00
!byte $00,$00,$00,$05,$05,$00,$00,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b
!byte $0b,$00,$00,$00,$00,$00,$05,$05,$00,$00,$00,$00,$00,$00,$0b,$0a
!byte $0a,$0a,$0a,$0b,$0b,$00,$00,$00,$00,$08,$08,$05,$05,$08,$00,$00
!byte $00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00,$08,$08,$08,$05
!byte $08,$08,$08,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$08
!byte $08,$08,$08,$08,$08,$08,$08,$08,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b
!byte $0b,$00,$00,$08,$08,$07,$08,$08,$08,$07,$08,$08,$00,$00,$0b,$0a
!byte $0a,$0a,$0a,$0b,$0b,$00,$08,$08,$07,$07,$08,$08,$08,$07,$07,$08
!byte $08,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$08,$08,$08,$08,$08,$07
!byte $08,$08,$08,$08,$08,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$08,$08
!byte $08,$08,$08,$07,$08,$08,$08,$08,$08,$00,$0b,$0a,$0a,$0a,$0a,$0b
!byte $0b,$00,$08,$08,$07,$08,$08,$08,$08,$08,$07,$08,$08,$00,$0b,$0a
!byte $0a,$0a,$0a,$0b,$0b,$00,$00,$08,$07,$07,$08,$07,$08,$07,$07,$08
!byte $00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$08,$08,$07,$08,$07
!byte $08,$07,$08,$08,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00
!byte $08,$08,$08,$08,$08,$08,$08,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b
!byte $0b,$00,$00,$00,$00,$08,$08,$08,$08,$08,$00,$00,$00,$00,$0b,$0a
!byte $0a,$0a,$0a,$0b,$0b,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
!byte $00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00,$00,$00,$00,$00
!byte $00,$00,$00,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00
!byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b
!byte $0b,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0b,$0a
!byte $0a,$0a,$0a,$0b,$0b,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
!byte $00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00,$00,$00,$00,$00
!byte $00,$00,$00,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b,$0b,$00,$00,$00
!byte $00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0b,$0a,$0a,$0a,$0a,$0b
!byte $0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b,$0b
!byte $0b,$0b,$0b,$0b


